# Generated by Django 3.2.5 on 2021-07-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Crudapp',
        ),
    ]
